export const MESSAGE_TYPES = {
  // Plugin to UI messages
  RUN_CODE: 'RUN_CODE',
  FRAME_SELECTED: 'FRAME_SELECTED',
  AI_PROMPT: 'AI_PROMPT',
  GET_FRAMES: 'GET_FRAMES',
  TOGGLE_LOCK: 'TOGGLE_LOCK',
  TOGGLE_AUTO_REFRESH: 'TOGGLE_AUTO_REFRESH',
  
  // UI to Plugin messages
  EXECUTION_RESULT: 'EXECUTION_RESULT',
  FRAMES_UPDATED: 'FRAMES_UPDATED',
  PLUGIN_READY: 'PLUGIN_READY',
  LOCK_STATE_UPDATED: 'LOCK_STATE_UPDATED',
  AUTO_REFRESH_STATE_UPDATED: 'AUTO_REFRESH_STATE_UPDATED'
} as const;

export const LOG_TYPES = {
  LOG: 'log',
  ERROR: 'error',
  TIMING: 'timing',
  SUCCESS: 'success'
} as const;
